export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const UPDATE_PRODUCT_QUANTITY = "UPDATE_PRODUCT_QUANTITY";
export const FETCH_CART = "FETCH_CART";
export const UPDATE_CART = "UPDATE_CART";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const SHOW_ERROR = "SHOW_ERROR";
export const HIDE_ERROR = "HIDE_ERROR";
